"""Actualiza modelos roles

Revision ID: 6921b4e7b1b0
Revises: edd5ab9caba6
Create Date: 2025-06-20 12:31:18.458087

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '6921b4e7b1b0'
down_revision: Union[str, Sequence[str], None] = 'edd5ab9caba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
