"""Actualiza modelos con extend_existing

Revision ID: 9731e302ed85
Revises: 6921b4e7b1b0
Create Date: 2025-06-20 12:37:10.360761

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '9731e302ed85'
down_revision: Union[str, Sequence[str], None] = '6921b4e7b1b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
