"""Agregar campo stock_minimo a productos

Revision ID: e7a3f75fb8fc
Revises: efd3fc0b6d0e
Create Date: 2025-06-19 12:16:53.954046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7a3f75fb8fc'
down_revision: Union[str, Sequence[str], None] = 'efd3fc0b6d0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('stock_minimo', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'stock_minimo')
    # ### end Alembic commands ###
