"""Actualiza modelos

Revision ID: edd5ab9caba6
Revises: f2bd40999aa3
Create Date: 2025-06-20 12:24:56.228975

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'edd5ab9caba6'
down_revision: Union[str, Sequence[str], None] = 'f2bd40999aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
