"""create usuarios y roles

Revision ID: efd3fc0b6d0e
Revises: 
Create Date: 2025-06-16 16:59:49.319246

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'efd3fc0b6d0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
