"""Actualiza modelos y tabla usuario_rol

Revision ID: f2bd40999aa3
Revises: 57a1009fc266
Create Date: 2025-06-20 12:14:39.362016

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'f2bd40999aa3'
down_revision: Union[str, Sequence[str], None] = '57a1009fc266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
