name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar Ruff (linter)
        run: |
          cd backend
          ruff check app tests

      - name: Ejecutar tests con Pytest
        env:
          PYTHONPATH: ./backend
          DATABASE_URL: sqlite:///./inventario.db
        run: |
          cd backend
          pytest -v
