name: CI - Tests y Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Linter + Tests
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Instalar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Cambiá si usás otra versión

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar Ruff (linter)
      run: |
        ruff check app tests

    - name: Crear base de datos con Alembic
      env:
        DATABASE_URL: sqlite:///./inventario.db
      run: |
        alembic upgrade head

    - name: Ejecutar Tests con Pytest
      env:
        DATABASE_URL: sqlite:///./inventario.db
      run: |
        pytest -v tests/
